pipeline {
    agent any
    stages {
        stage('Prepare') {
            parallel {
                stage('Clear') {
                    steps {
                        sh 'rm -rf allure-results'
                    }
                }
                stage('Build') {
                    steps {
                        sh 'mvn install -DskipTests'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh "mvn test -Dgroups='${Tag}'"
            }
        }
    }
    post {
        always {
            allure([
                    includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'allure-results']]
            ])
        }
    }
}